# Copyright (c) 2018 Julian Prasetyo <picobug.jp@gmail.com>
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

FROM traefik:alpine

LABEL maintainer="Julio Pico <picobug.jp@gmail.com>"
