# Copyright (c) 2018 Julian Prasetyo <picobug.jp@gmail.com>
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

FROM picobug/swoole

LABEL maintainer="Julio Pico <picobug.jp@gmail.com>"

EXPOSE 1215

CMD ["php", "artisan", "swoole:http", "start"]